print("Sir")
print("Madam")
print("Pure Methods")
print("Madam")
print("MacBook Pro")
print("MacBook Mini")
print("HP Omen")
print("The ASUS")
print("Dell")
print("Alienware")

print("Car")
print("2nd car")
print("3rd car")
print("4th car")
print("5th car")
print("6th car")
print("7th car")
print("8th car")
