console.log("I own it!");
console.log("I own it!");
console.log("I will try it again");
console.log("A little more testing");
console.log("Last One");
console.log("Not enough");
console.log("Researching");
console.log("Solid");
console.log("New video");
console.log("Last video");